#!/bin/bash

#   Filename    :   subvolume-defragment
#   Filetype    :   Bash shell script
#   Comment     :   
#   Description :   defrags a btrfs subvolume

# Target_Subvol example: Target_Subvol="/mnt/HDD/Ubuntu"
Target_Subvol=""

btrfs filesystem defragment "$Target_Subvol"
