#!/bin/bash

#   File: /et/cron.daily/custom_backup
#   Type: Bash script

#   Backup user files (daily) to '/Backup/' disk
#   Copyright (C) 2014 fkol-k4 (fkolyvas@gmail.com)

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation version 2.

#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.

#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc.,
#   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


#if [[ -d /Files ]] && [[ -d /Backup ]]; then
#    rsync -aqz --log-file=/Backup/rsync-backup.log /Files/ /Backup/
#fi
